name: Build

on:
  push:
    branchs:
      - master
      - feature-liuzx-ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |

          apt update

          apt install curl build-essential -y

          apt install linux-headers-$(uname -r) -y

          curl -fsSL https://xmake.io/shget.text | bash

      - name: Configure XMake
        working-directory: ${{github.workspace}}
        run: |

          alias xmake=~/.local/bin/xmake

          xmake --root f -m release --linux-headers=/usr/src/linux-headers-$(uname -r)/
      
      - name: Build Targets
        working-directory: ${{github.workspace}}
        run: |

          alias xmake=~/.local/bin/xmake

          xmake --root build
