name: Build

on:
  push:
    branchs:
      - master
      - feature-liuzx-ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |

          apt update

          apt install build-essential

          curl -fsSL https://xmake.io/shget.text | bash

      - name: Configure XMake
        working-directory: ${{github.workspace}}
        run: |

          xmake f --linux-headers=/usr/src/linux-headers-${shell uname -r}/
      
      - name: Build Targets
        working-directory: ${{github.workspace}}
        run: |

          xmake
