name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "v*"
  schedule:
    - cron: 0 4 * * *

# see more at https://github.com/DavidingPlus/nvmixfs/issues/1
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/davidingplus/nvmixfs-docker-runtime:latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Toolchain
        run: |
          curl --version
          gcc -v
          g++ -v
          python3 -V
          pip --version
          cmake --version
          git --version
          xmake --version
          conan --version

      - name: Detect Kernel Headers
        run: |
          KERNEL_HEADER_DIR=$(find /usr/src -maxdepth 1 -type d -name 'linux-headers-*' | head -n 1)

          echo "KERNEL_HEADER_DIR=${KERNEL_HEADER_DIR}"

          if [ -z "$KERNEL_HEADER_DIR" ]; then
            echo "Linux headers not found!"
            exit 1
          fi

          echo "KERNEL_HEADER_DIR=${KERNEL_HEADER_DIR}" >> $GITHUB_ENV

      - name: Configure XMake
        working-directory: ${{github.workspace}}
        run: |

          export XMAKE_ROOT=y

          xmake f -m release --linux-headers="${KERNEL_HEADER_DIR}/" -y

      - name: Build Targets
        working-directory: ${{github.workspace}}
        run: |

          export XMAKE_ROOT=y

          xmake build
