name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "v*"
  schedule:
    - cron: 0 4 * * *

# see more at https://github.com/DavidingPlus/nvmixfs/issues/1
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/davidingplus/nvmixfs-docker-runtime:latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure XMake
        working-directory: ${{github.workspace}}
        run: |

          alias xmake="~/.local/bin/xmake"
          export XMAKE_ROOT=y

          xmake f -m release --linux-headers=/usr/src/linux-headers-${KERNEL_VERSION}/ -y

      - name: Build Targets
        working-directory: ${{github.workspace}}
        run: |

          alias xmake="~/.local/bin/xmake"
          export XMAKE_ROOT=y

          xmake build
